name: Build workflow
run-name: Build workflow
on:
  workflow_dispatch:
  push:
    branches:
    - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}
    strategy:
      matrix:
        perl-version:
        - '5.24'
        - '5.26'
        - '5.28'
        - '5.30'
        - '5.32'
        - '5.34'
    steps:
    - uses: actions/checkout@v4
    - name: Install Dzil
      run: cpm install -g --no-test Dist::Zilla Dist::Zilla::App::Command::cover ExtUtils::MakeMaker
    - name: Install dzil author dependencies
      run: |
        cpm install --no-test -g \
        -w 2 \
        --mirror=http://cpan.cpantesters.org/ $(dzil authordeps --missing)
    - name: Install dist deps
      run: |
        # see https://github.com/team-at-cpan/Dist-Zilla-Plugin-PodInherit/issues/1 to check why we not use
        # dzil listdeps --missing directly here
        cpanm -n --installdeps .
        dzil listdeps --author --missing --cpanm-versions | xargs cpanm -n
    - name: Install Redis Server
      run: apt-get install -y redis
    - name: Debug cover command
      run: dzil help cover
    - name : Run Tests
      run: dzil smoke --release --author && dzil cover && dzil xtest
